name: 🚀 Pangloin deploy

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    uses: dyne/workflows/.github/workflows/node-staging-deploy.yml@main
    secrets: inherit
